app = "sll"
primary_region = "sin"

[env]
NODE_ENV = "production"
TRUST_PROXY = "1"

[http_service]
auto_start_machines = true
auto_stop_machines = "off"
force_https = true
internal_port = 8_080
min_machines_running = 0

  [[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  path = "/health"
  timeout = "5s"

[[vm]]
memory = "256mb"
size = "shared-cpu-1x"
